[theme]
name = "noctalia"

[colors]
AlertInfo = "#3cb371"
AlertWarn = "#d95757"
AlertError = "#645a79"
Annotation = "#231e32"
Base = "#ef9b27"
Guidance = "#3cb371"
Important = "#6c82c4"
Title = "#ef9b27"
Muted = "#ef9b27"
