[theme]
name = "noctalia"

[colors]
AlertInfo = "#b4befe"
AlertWarn = "#f38ba8"
AlertError = "#6c7086"
Annotation = "#3a3b50"
Base = "#cba6f7"
Guidance = "#b4befe"
Important = "#89dceb"
Title = "#cba6f7"
Muted = "#cba6f7"
