#[templates.niri]
#input_path = "~/.config/noctalia/templates/niri.kdl"
#output_path = "~/.config/niri/colors.kdl"
#post_hook = "niri msg action reload-config"

#[templates.nvim-base16]
#input_path = "~/.config/nvim/lua/matugen-template.lua"
#output_path = "~/.config/nvim/lua/matugen.lua"
#post_hook = 'pkill -SIGUSR1 nvim'

#[templates.background]
#input_path = "~/.config/niri/configTemplate.kdl"
#output_path = "~/.config/niri/config.kdl"
#post_hook = "niri msg action reload-config"

#### Above this is v4 configs ####

[theme.templates.user.fastfetch]
input_path = "~/.config/fastfetch/configTemplate.jsonc"
output_path = "~/.config/fastfetch/config.jsonc"

[theme.templates.user.atuin]
input_path = "~/.config/atuin/themes/template.toml"
output_path = "~/.config/atuin/themes/noctalia.toml"

[theme.templates.user.oh_my_posh]
input_path  = "$XDG_CONFIG_HOME/oh-my-posh/noctalia-template.json"
output_path = "$XDG_CONFIG_HOME/oh-my-posh/noctalia.json"

[theme.templates.user.cliamp]
input_path  = "~/.config/cliamp/themes/noctaliaTemplate"
output_path = "~/.config/cliamp/themes/noctalia.toml"

[theme.templates.user.lualine]
input_path = "~/.config/nvim/lua/themes/noctaliaTemplate.lua"
output_path = "~/.config/nvim/lua/themes/noctalia.lua"
